version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_sites
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: neko
      POSTGRES_PASSWORD: 1313
    ports:
      - "5432:5432"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  backend:
    container_name: backend
    build: 
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: neko@example.com
      PGADMIN_DEFAULT_PASSWORD: 1313
    volumes:
      - pgadmin_data:/var/lib/pgadmin


volumes:
  pgadmin_data:
