"""add data

Revision ID: 0c97ca86a7d8
Revises: 361f5649ebb9
Create Date: 2023-11-22 03:13:40.504580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c97ca86a7d8"
down_revision: Union[str, None] = "361f5649ebb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "INSERT INTO countries (id, name, history) VALUES (1, 'Франция', 'Французская кухня славится своим изысканным вкусом и богатством кулинарных традиций. Она воплощает в себе искусство гастрономии, отличаясь высоким качеством ингредиентов и непревзойденной кулинарной мастерством. Французские блюда подчеркивают важность сезонности, что придает им особый аромат и неповторимый вкус. Среди знаменитых французских блюд можно выделить бифштекс медальон, кулинарное произведение искусства, а также бугендское говяжье рагу, замечательно сочетающее в себе ароматные специи и нежное мясо. Французская пастели, красочные десерты и разнообразные сыры дополняют кулинарное наследие этой великой кухни.')"
    )
    op.execute(
        "INSERT INTO countries (id, name, history) VALUES (2, 'Япония', 'Японская кухня, известная своей изысканностью и утонченностью, предлагает неповторимый вкусовой опыт благодаря свежим и высококачественным ингредиентам. В ней особое внимание уделяется балансу текстур и визуальному оформлению блюд. Суши, роллы и сашими — иконы японской гастрономии — привносят в меню утонченные сочетания рыбы и риса. Изюминкой японской кухни являются также традиционные гарниры, такие как мизо-суп и вакаме, которые покоряют своим насыщенным вкусом и питательными свойствами. Благодаря вниманию к деталям и стремлению к гармонии во всем, японская кухня завоевала популярность и признание по всему миру.')"
    )
    op.execute(
        "INSERT INTO countries (id, name, history) VALUES (3, 'Италия', 'Итальянская кухня — это настоящее искусство кулинарии, которое покорило весь мир своим превосходным вкусом и разнообразием блюд. В ее основе лежит уважение к натуральным и свежим ингредиентам, которые обыгрываются с простотой и великолепно сочетаются в каждом блюде. Пицца и паста — символы итальянской гастрономии, предлагая бесконечное разнообразие начинок и соусов. Кроме того, традиционные ризотто, минестроне и оливковое масло являются неотъемлемой частью кулинарного наследия Италии. Десерты, такие как тирамису и панна-котта, завершают ужин с изыском и утонченностью. Итальянская кухня — это гармония вкусов и ароматов, принесенная из сердца Средиземноморья.')"
    )

    op.execute("INSERT INTO categories (id,name) VALUES (1,'Супы')")
    op.execute("INSERT INTO categories (id,name) VALUES (2,'Салаты')")
    op.execute("INSERT INTO categories (id,name) VALUES (3,'Мясо')")
    op.execute("INSERT INTO categories (id,name) VALUES (4,'Рыба')")

    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (1, 'Рамэн', 'Сварите рамен согласно инструкции на упаковке. Отцедите. В большой кастрюле смешайте куриный бульон, соевый соус, мирин, имбирь и прогрейте на среднем огне. Разложите рамен по мискам, добавьте бульон, а затем остальные ингредиенты (лук, шпинат, яйца и курицу).', 2, 1)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (2, 'Мисо суп', 'В кастрюле смешайте даш и воду. Нагревайте на среднем огне, пока не доведете до кипения. Взболтайте пасту мисо в небольшой миске с небольшим количеством горячей воды, чтобы получилась гладкая паста. Добавьте мисо-пасту в кипящий бульон и перемешайте, пока она полностью не растворится. Добавьте тофу, зеленый лук, имбирь и соевый соус. Готовьте на среднем огне около 5-7 минут, пока тофу не прогреется. Разлейте суп по чашкам и украсьте нори.', 2, 1)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (3, 'Удон суп', 'Сварите удон согласно инструкции на упаковке. Отцедите. В большой кастрюле смешайте куриный бульон, соевый соус, мирин, грибы и морковь. Прогрейте на среднем огне. Разложите удон по мискам, добавьте бульон, а затем овощи.', 2, 1)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (4, 'Том ям', 'В кастрюле смешайте куриный бульон, соевый соус, лимонный сок, рыбный соус, том-ям пасту и сахар. Прогрейте на среднем огне. Добавьте креветки, грибы, чеснок и имбирь. Варите до готовности креветок (2-3 минуты). Подавайте горячим.', 2, 1)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (5, 'Салат с японской майонезной заправкой', 'В большой миске смешайте курицу, огурцы, морковь и яйца. Добавьте японскую майонезную заправку и нежно перемешайте до равномерного покрытия.', 2, 2)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (6, 'Гома-э дофу (салат с кунжутным соусом)', 'Выложите тофу на тарелку. В миске смешайте кунжутную пасту, соевый соус, мирин, сахар и имбирь. Полейте этой соусом тофу. Украсьте зеленым луком и кунжутом.', 2, 2)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (7, 'Салат с водорослями', 'В большой миске смешайте водоросли, огурцы и морковь. В небольшой миске смешайте рисовый уксус, сахар, имбирь и соевый соус до растворения сахара. Полейте салат приготовленным соусом.', 2, 2)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (8, 'Салат с огурцом и сезамом', 'В миске смешайте огурцы, рисовый уксус, сахар, тамари и кунжутное масло. Украсьте салат обжаренными семенами кунжута.', 2, 2)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (9, 'Тереяки с курицей', 'В средней миске смешайте соевый соус, мирин, сахар, чеснок и имбирь. Это будет ваша терияки-подливка. Разогрейте растительное масло в большой сковороде на среднем огне. Обжаривайте курицу до золотистой корочки с обеих сторон, примерно по 2-3 минуты с каждой стороны. Влейте терияки-подливку в сковороду к курице. Доведите до кипения и уменьшите огонь. Готовьте под крышкой на среднем огне около 10 минут или до тех пор, пока курица не приготовится полностью. Подавайте терияки с курицей горячим, посыпанным мелко нарезанным зеленым луком и кунжутом.', 2, 3)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (10, 'Сукияки', 'В кастрюле смешайте даш, соевый соус, мирин и сахар. Прогрейте на среднем огне. Разложите говядину, тофу, шири-фундо, шинако, лук и чеснок в кастрюле. Варите до готовности мяса и овощей.', 2, 3)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (11, 'Тонкацу', 'Постучите мясо, посолите и поперчите. Обваляйте в муке, затем в яйце и наконец в панировке. Разогрейте масло в сковороде и обжаривайте котлеты с обеих сторон до золотистой корочки. Отцедите от лишнего масла, порежьте котлеты полосками. Посыпьте молотым кунжутом, подавайте с тонкацу соусом.', 2, 3)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (12, 'Якитори', 'В небольшой кастрюле смешайте соевый соус, мирин, сахар, чеснок и имбирь. Прогрейте на среднем огне, пока сахар не растворится. Нанизывайте куриные кусочки на деревянные шпажки. Обваляйте в приготовленном соусе. Обжаривайте на гриле или в духовке до готовности. Украсьте зеленым луком.', 2, 3)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (13, 'Суши с лососем', 'Готовим рис: промываем его под холодной водой до полного удаления крахмала. Затем варим в соотношении 1:1,5 с водой до готовности. Готовим уксусный соус: смешиваем рисовый уксус, сахар и соль в небольшой кастрюле. Разогреваем на слабом огне, до полного растворения сахара. Остужаем. Размешиваем приготовленный соус с рисом, остужаем вентилируя воздухом, крошим его деревянной ложкой до получения нужной консистенции. Нарезаем лосось тонкими полосками. Готовим роллы: кладем нори на суши-мат, распределяем слой риса, оставив свободным верхний край. Увлажняем руки водой, разглаживаем рис. Переворачиваем нори рисом вниз. Выкладываем начинку в центр: лосось и другие предпочитаемые ингредиенты. С помощью суши-мата аккуратно скручиваем ролл, обертываем его в пленку и формируем. Остужаем в морозильнике в течение 10 минут. Режем роллы острой ножом на 6-8 кусочков. Подаем с васаби и соевым соусом.', 2, 4)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (14, 'Терияки с тунцом', 'В небольшой кастрюле смешайте соевый соус, мирин, сахар, терияки соус, чеснок и имбирь. Прогрейте на среднем огне, пока сахар не растворится. Обваляйте тунец в приготовленном соусе и обжаривайте в горячей сковороде до желаемой степени прожарки.', 2, 4)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (15, 'Яки-сакана', 'В небольшой кастрюле смешайте соевый соус, мирин, сахар и имбирь. Прогрейте на среднем огне, пока сахар не растворится. Гриль семгу до готовности, регулируя время в зависимости от толщины кусков. Полейте приготовленным соусом.', 2, 4)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (16, 'Мисо-глазированный', 'В небольшой кастрюле смешайте мисо-пасту, мирин, сахар и саке. Прогрейте на среднем огне, пока сахар не растворится. Готовьте кабачки до готовности, обмакивая их в мисо-смеси в течение последних 5-7 минут приготовления.', 2, 4)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (17, 'Луковый суп', 'Разогрейте масло в кастрюле и обжарьте лук до золотистой корочки. Добавьте вино и варите до его полного испарения. Влейте говяжий бульон, посолите, поперчите, добавьте тимьян. Варите около 30 минут. Запеките багет с сыром до золотистой корочки. Разлейте суп по горшкам, положите на каждый ломтик багета с сыром.', 1, 1)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (18, 'Буйабес (Bouillabaisse)', 'Обжарить лук, чеснок, добавить помидоры и специи. Влить бульон, варить 15 минут, затем добавить рыбу и креветки.', 1, 1)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (19, 'Гаспачо (Gazpacho)', 'Рецепт гаспачо', 1, 1)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (20, 'Устричный суп', 'Варить бульон с вином, добавить открывшиеся устрицы. Убрать устрицы из раковины, добавить мясо в суп. В конце добавить сливочное масло.', 1, 1)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (21, 'Ницца', 'Смешать нарезанный тунец, картошку, помидоры и маслины. Полить оливковым маслом.', 1, 2)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (22, 'Капрезе', 'Нарезать помидоры и моцареллу, выложить слоями. Посыпать мелко нарезанным базиликом, полить маслом.', 1, 2)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (23, 'Салат с улипками (Salade aux Escargots)', 'Обжарить улиток с чесноком и петрушкой на оливковом масле. Уложить на листья салата.', 1, 2)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (24, 'Салат с ростбифом (Salade de Roastbeef)', 'Нарезать ростбиф, выложить на рукколу. Посыпать тертым пармезаном и грецкими орехами.', 1, 2)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (25, 'Беф Бургиньон (Boeuf Bourguignon)', 'Обжарить мясо, добавить лук, морковь, грибы, залить вином, тушить 2-3 часа.', 1, 3)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (26, 'Курица в вине (Coq au Vin)', 'Обжарить цыпленка, бекон, грибы, залить вином, тушить 1,5-2 часа.', 1, 3)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (27, 'Конфит утки (Canard Confît)', 'Подготовить утиные ножки с солью, перцем, чесноком, запечь в собственном жире.', 1, 3)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (28, 'Филе молодого кролика с горчичным соусом', 'Обжарить филе, добавить горчицу, сливки, довести до загустения.', 1, 3)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (29, 'Лосось в соусе бурбланк (Saumon à la Bourguignonne)', 'Обжарить лосось в масле с чесноком и петрушкой.', 1, 4)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (30, 'Тунец в перцевой корке (Thon en Croûte de Poivre)', 'Обвалять тунец в молотом перце, обжарить.', 1, 4)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (31, 'Муллет винный (Mulet au Vin Rouge)', 'Тушить рыбу с луком, морковью и вином.', 1, 4)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (32, 'Филе трески с пюре из картофеля и соусом из лимона и каперсов', 'Варите картошку до готовности, отцеживаете и варите пюре с добавлением масла, соли и перца. Рыбу посолите и поперчите, обжаривайте на сковороде с небольшим количеством масла до золотистой корочки с обеих сторон. В небольшой кастрюле смешайте сок и цедру лимона, каперсы и сливки. Грейте на слабом огне, пока соус не загустеет. Уложите филе трески на тарелку, подайте с пюре из картофеля и полейте соусом. Посыпьте мелко нарезанной зеленью.', 1, 4)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (33, 'Минестроне', 'В глубокой кастрюле разогрейте оливковое масло и обжарьте лук, морковь, сельдерей и картошку до мягкости. Добавьте томаты и бульон, доведите до кипения, затем уменьшите огонь и варите 30 минут. Добавьте макароны и варите еще 10-15 минут до готовности макарон. Добавьте бобы и готовьте еще 5-7 минут. Приправьте солью и перцем по вкусу. Подавайте с натертым пармезаном.', 3, 1)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (34, 'Риболлита', 'Замочите фасоль в воде на ночь. Следующего дня отварите до готовности. В большой кастрюле обжарьте лук, морковь и сельдерей на оливковом масле до мягкости. Добавьте помидоры и фасоль. Залейте водой так, чтобы она покрыла все ингредиенты, и варите около часа. Добавьте шпинат и варите еще 10 минут. Подавайте с кусками поджаренного хлеба.', 3, 1)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (35, 'Крем-суп с брокколи', 'Обжарьте лук на оливковом масле до прозрачности. Добавьте картошку и брокколи, обжаривайте еще несколько минут. Залейте куриной бульоном и варите до мягкости картошки и брокколи. Разотрите суп блендером до получения однородной массы. Добавьте сливки, пармезан, соль и перец по вкусу. Подогрейте и подавайте.', 3, 1)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (36, 'Зуппа ди песче', 'В большой кастрюле обжарьте лук, морковь и картошку на оливковом масле до мягкости. Добавьте помидоры, рыбный бульон и вино. Варите около 30 минут. Добавьте рыбу и варите еще 10-15 минут до готовности рыбы. Подавайте горячим.', 3, 1)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (37, 'Инсалата Русса', 'Сварите картофель, морковь и яйца до готовности. Остудите и очистите. Нарежьте картошку и морковь кубиками, нарежьте яйца кубиками. Добавьте горошек. Посолите, поперчите и добавьте майонез. Тщательно все перемешайте. Подавайте в охлажденном виде.', 3, 2)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (38, 'Панзанелла', 'Замочите хлеб в воде на несколько минут, затем выжмите излишек влаги. Нарежьте помидоры, огурец и лук кубиками, добавьте зелень. Перемешайте с хлебом, полейте оливковым маслом и уксусом, если используете. Посолите и поперчите по вкусу.', 3, 2)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (39, 'Инсалата Каппоне', 'Нарежьте тунец, яйца, лук и помидоры кубиками. Добавьте зелень, посолите и поперчите по вкусу. Полейте оливковым маслом и лимонным соком.', 3, 2)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (40, 'Руккола с пармезаном', 'Выложите рукколу на тарелку. Посыпьте тертым пармезаном. Полейте оливковым маслом и лимонным соком. Посолите и поперчите по вкусу.', 3, 2)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (41, 'Оссобуко', 'Обваляйте голени в муке и обжаривайте на оливковом масле до золотистости. Выньте мясо, добавьте лук, морковь и сельдерей, обжаривайте до мягкости. Верните мясо в кастрюлю, добавьте томаты и куриной бульон, варите около 2 часов до готовности. Подавайте с жареным рисом или гренками.', 3, 3)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (42, 'Лазанья', 'Обжарьте лук и чеснок на оливковом масле, добавьте фарш и обжаривайте до золотистости. Добавьте томаты и варите около 30 минут. Варите лазанью до готовности, затем соберите слои: соус, листы лазаньи, моцарелла и пармезан. Повторите несколько раз. Запекайте в предварительно разогретой до 180°C духовке около 30 минут.', 3, 3)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (43, 'Полло алла Качаторра', 'Обжаривайте куриные бедра на оливковом масле до золотистости. Выньте их из сковороды. В той же сковороде обжаривайте лук, перец и чеснок. Добавьте томаты и варите около 30 минут. Верните курицу в сковороду, добавьте оливки и базилик. Варите еще 15-20 минут.', 3, 3)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (44, 'Сальтимбокка', 'Заверните каждый кусок мяса в ветчину, затем в лосось и лист шпината. Закрепите все при помощи зубочисток. Обжарьте в сливочном масле до золотистости со всех сторон. Полейте вином и варите еще несколько минут до готовности.', 3, 3)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (45, 'Осьминог в собственном соку', 'Очистите осьминога от кишок и обработайте его вместе с лимоном (сок и цедра) и чесноком. Обжаривайте на оливковом масле до золотистости, затем добавьте петрушку.Варите около 45 минут в собственном соку. Периодически помешивайте. Подавайте горячим.', 3, 4)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (46, 'Фритто Мисто', 'Обваляйте морепродукты в муке, затем взбитом яйце. Обжаривайте на оливковом масле до золотистости. Подавайте с лимонными дольками, посыпанными солью и перцем.', 3, 4)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (47, 'Ризотто с морепродуктами', 'Обжаривайте лук и чеснок на оливковом масле до прозрачности. Добавьте рис и обжаривайте еще несколько минут. Залейте вино и доведите до кипения, дайте выкипеть алкоголю. Постепенно добавляйте горячий куриный бульон, постоянно помешивая, пока рис не станет мягким. В последние несколько минут варки добавьте морепродукты. Подавайте, посыпанным петрушкой.', 3, 4)"
    )
    op.execute(
        "INSERT INTO recipes (id, title, description, countries_id, categories_id) VALUES (48, 'Фарфалле с лимонным крем-соусом и креветками', 'Варите фарфалле в кипящей подсоленной воде до готовности. Отцедите. Обжаривайте креветки на оливковом масле до румяной корочки. Уберите их из сковороды. В той же сковороде добавьте сливки, чеснок, сок и цедру лимона. Готовьте несколько минут до загустения. Верните креветки в соус, добавьте фарфалле и петрушку. Перемешайте до обогрева. Подавайте горячим.', 3, 4)"
    )

    op.execute("INSERT INTO ingredients (id, name) VALUES (1,'Рамэн (лапша)')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (2,'Куриный бульон')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (3,'Соевый соус')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (4,'Мирин (рисовое вино)')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (5,'Имбирь')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (6,'Красный лук')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (7,'Шпинат')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (8,'Куриные яйца')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (9,'Куриное мясо')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (10,'Даш (водорослевый бульон)')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (11,'Паста мисо')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (12,'Тофу')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (13,'Зеленый лук')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (14,'Водоросли нори')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (15,'Удон (лапша)')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (16,'Грибы шитаке')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (17,'Морковь')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (18,'Лук-порей')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (19,'Креветки')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (20,'Лимонный сок')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (21,'Рыбный соус')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (22,'Том-ям паста')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (23,'Сахар')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (24,'Чеснок')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (25,'Огурец')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (26,'Японская майонезная заправка')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (27,'Кунжутная паста')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (28,'Кунжут')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (29,'Водоросли вакаме')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (30,'Рисовый уксус')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (31,'Кунжутное масло')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (32,'Тамари (подсоленный соевый соус)')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (33,'Растительное масло')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (34,'Луковица')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (35,'Говядина')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (36,'Шири-фундо (рисовая вермишель)')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (37,'Шинако (подсолнечные ростки)')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (38,'Свинные котлеты')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (39,'Мука')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (40,'Панировочные сухари')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (41,'Лосось')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (42,'Соль')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (43,'Рис')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (44,'Тунец')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (45,'Соус тереяки')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (46,'Филе семги')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (47,'Чёрная треска')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (48,'Саке')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (49,'Сливочное масло')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (50,'Говяжий бульон')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (51,'Белое вино')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (52,'Грюнгерский сыр')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (53,'Помидор')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (54,'Картофель')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (55,'Оливковое масло')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (56,'Красно винный уксус')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (57,'Устрицы')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (58,'Маслины')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (59,'Базилик')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (60,'Моцарелла')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (61,'Улитки')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (62,'Петрушка')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (63,'Ростбиф')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (64,'Руккола')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (65,'Пармезан')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (66,'Грецкие орехи')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (67,'Грибы')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (68,'Красное вино')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (69,'Бекон')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (70,'Куриная ножка')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (71,'Утиный жир')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (72,'Филе кролика')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (73,'Горчица')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (74,'Сливки')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (75,'Чёрный перец')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (76,'Рыба муллет')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (77,'Треска')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (78,'Капперсы')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (79,'Овощной бульон')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (80,'Стебель сельдерея')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (81,'Бобы')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (82,'Макаронные изделия')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (83,'Белая фасоль')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (84,'Хлеб')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (85,'Броколи')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (86,'Рыбный бульон')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (87,'Горох')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (88,'Майонез')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (89,'Телячья голень')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (90,'Лазанья')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (91,'Мясной фарш')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (92,'Оливки')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (93,'Ветчина')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (94,'Осьминог')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (95,'Лимон')")
    op.execute("INSERT INTO ingredients (id, name) VALUES (96,'Фарфалле')")

    # Рамэн
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (1, 200, 1, 1)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (2, 1000, 1, 2)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (3, 30, 1, 3)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (4, 30, 1, 4)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (5, 5, 1, 5)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (6, 100, 1, 6)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (7, 100, 1, 7)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (8, 90, 1, 8)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (9, 200, 1, 10)")
    # Мисо суп
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (10, 1000, 2, 10)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (11, 45, 2, 11)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (12, 100, 2, 12)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (13, 100, 2, 13)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (14, 5, 2, 5)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (15, 5, 2, 3)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (16, 100, 2, 14)")
    # Удон суп
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (17, 200, 3, 15)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (18, 1000, 3, 2)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (19, 30, 3, 3)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (20, 15, 3, 4)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (21, 100, 3, 16)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (22, 100, 3, 17)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (23, 100, 3, 18)")
    # Том ям
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (24, 1000, 4, 2)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (25, 200, 4, 19)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (26, 200, 4, 16)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (27, 30, 4, 3)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (28, 30, 4, 20)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (29, 10, 4, 21)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (30, 10, 4, 22)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (31, 5, 4, 23)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (32, 10, 4, 24)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (33, 5, 4, 5)")
    # Салат с японской майонезной заправкой
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (34, 200, 5, 9)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (35, 100, 5, 25)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (36, 100, 5, 17)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (37, 90, 5, 8)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (38, 30, 5, 26)")
    # Гома-э дофу (салат с кунжутным соусом)
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (39, 300, 6, 12)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (40, 30, 6, 27)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (41, 30, 6, 3)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (42, 15, 6, 4)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (43, 5, 6, 23)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (44, 5, 6, 5)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (45, 50, 6, 13)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (282, 10, 6, 28)")
    # Салат с водорослями
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (46, 50, 7, 29)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (47, 100, 7, 25)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (48, 50, 7, 17)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (49, 30, 7, 30)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (50, 15, 7, 23)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (51, 5, 7, 5)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (52, 5, 7, 3)")
    # Салат с огурцом и сезамом
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (53, 300, 8, 25)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (54, 30, 8, 30)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (55, 15, 8, 23)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (56, 30, 8, 32)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (57, 5, 8, 31)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (58, 5, 8, 28)")
    # Тереяки с курицей
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (59, 400, 9, 9)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (60, 500, 9, 3)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (61, 250, 9, 4)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (62, 30, 9, 23)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (63, 10, 9, 24)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (64, 5, 9, 5)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (65, 30, 9, 33)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (66, 50, 9, 13)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (67, 10, 9, 28)")
    # Сукияки
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (68, 300, 10, 35)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (69, 200, 10, 12)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (70, 100, 10, 36)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (71, 200, 10, 37)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (72, 2000, 10, 10)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (73, 45, 10, 3)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (74, 30, 10, 4)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (75, 30, 10, 23)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (76, 150, 10, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (77, 10, 10, 24)")
    # Тонкацу (свиные отбивные)
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (78, 250, 11, 38)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (79, 40, 11, 39)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (80, 100, 11, 8)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (81, 100, 11, 40)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (82, 30, 11, 33)")
    # Якитори (куриные шашлычки)
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (83, 400, 12, 9)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (84, 45, 12, 3)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (85, 250, 12, 4)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (86, 30, 12, 23)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (87, 10, 12, 24)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (88, 5, 12, 5)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (89, 50, 12, 13)")
    # Суши с лососем
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (90, 250, 13, 41)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (91, 250, 13, 43)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (92, 50, 13, 30)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (93, 30, 13, 23)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (94, 5, 13, 42)")
    # Терияки с тунцом
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (95, 400, 14, 44)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (96, 60, 14, 3)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (97, 30, 14, 4)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (98, 30, 14, 23)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (99, 10, 14, 45)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (100, 10, 14, 24)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (101, 5, 14, 5)")
    # Яки-сакана
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (102, 500, 15, 46)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (103, 60, 15, 3)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (104, 30, 15, 4)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (105, 30, 15, 23)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (106, 5, 15, 5)")
    # Мисо-глазированный
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (107, 500, 16, 47)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (108, 50, 16, 11)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (109, 30, 16, 4)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (110, 30, 16, 23)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (111, 30, 16, 48)")
    # Луковый суп
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (112, 100, 17, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (113, 30, 17, 49)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (114, 1000, 17, 50)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (115, 100, 17, 51)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (116, 100, 17, 52)")
    # Буйабес
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (117, 250, 18, 44)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (118, 50, 18, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (119, 10, 18, 24)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (120, 200, 18, 53)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (121, 250, 18, 19)")
    # Гаспачо
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (122, 300, 19, 53)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (123, 100, 19, 25)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (124, 50, 19, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (125, 10, 19, 24)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (126, 50, 19, 55)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (127, 50, 19, 56)")
    # Устричный суп
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (128, 1800, 20, 57)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (129, 1000, 20, 50)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (130, 100, 20, 51)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (131, 50, 20, 49)")
    # Ницца
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (132, 200, 21, 44)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (133, 200, 21, 54)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (134, 100, 21, 53)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (135, 50, 21, 58)")
    # Капрезе
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (136, 250, 22, 53)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (137, 50, 22, 55)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (138, 50, 22, 59)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (139, 50, 22, 60)")
    # Салат с улитками
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (140, 200, 23, 61)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (141, 10, 23, 24)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (142, 50, 23, 62)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (143, 30, 23, 55)")
    # Салат с ростбифом
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (144, 1000, 24, 63)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (145, 250, 24, 53)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (146, 50, 24, 64)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (147, 200, 24, 65)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (148, 50, 24, 66)")
    # Беф Бургиньон
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (149, 800, 25, 35)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (150, 200, 25, 17)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (151, 50, 25, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (152, 200, 25, 67)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (153, 250, 25, 68)")
    # Курица в вине (Coq au Vin)
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (154, 1000, 26, 9)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (155, 250, 26, 68)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (156, 200, 26, 69)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (157, 200, 26, 67)")
    # Конфит утки (Canard Confît)
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (158, 600, 27, 70)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (159, 10, 27, 42)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (160, 50, 27, 71)")
    # Филе молодого кролика с горчичным соусом
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (161, 1000, 28, 72)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (162, 10, 28, 42)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (163, 100, 28, 73)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (164, 100, 28, 74)")
    # Лосось в соусе бурбланк (Saumon à la Bourguignonne)
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (165, 1000, 29, 41)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (166, 100, 29, 49)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (167, 20, 29, 24)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (168, 50, 29, 62)")
    # Тунец в перцевой корке (Thon en Croûte de Poivre)
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (169, 1000, 30, 44)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (170, 50, 30, 55)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (171, 50, 30, 75)")
    # Муллет винный (Mulet au Vin Rouge)
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (172, 1000, 31, 76)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (173, 200, 31, 68)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (174, 100, 31, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (175, 150, 31, 17)")
    # Филе трески с пюре из картофеля и соусом из лимона и каперсов
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (176, 1000, 32, 77)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (177, 500, 32, 54)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (178, 50, 32, 55)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (179, 30, 32, 78)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (180, 100, 32, 74)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (181, 30, 32, 20)")
    # Минестроне
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (182, 2000, 33, 79)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (183, 100, 33, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (184, 70, 33, 17)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (185, 40, 33, 80)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (186, 150, 33, 54)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (187, 400, 33, 53)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (188, 400, 33, 81)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (189, 100, 33, 82)")
    # Риболлита
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (190, 200, 34, 83)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (191, 200, 34, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (192, 140, 34, 17)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (193, 80, 34, 80)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (194, 400, 34, 53)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (195, 200, 34, 7)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (196, 200, 34, 84)")
    # Крем-суп с брокколи
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (197, 500, 35, 85)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (198, 100, 35, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (199, 200, 35, 54)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (200, 1000, 35, 2)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (201, 100, 35, 74)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (202, 100, 35, 65)")
    # Зуппа ди песче
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (203, 500, 36, 41)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (204, 100, 36, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (205, 140, 36, 17)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (206, 200, 36, 54)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (207, 1000, 36, 86)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (208, 400, 36, 53)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (209, 100, 36, 51)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (210, 30, 36, 55)")
    # Инсалата Русса
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (211, 500, 37, 54)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (212, 140, 37, 17)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (213, 200, 37, 87)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (214, 240, 37, 8)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (215, 150, 37, 88)")
    # Панзанелла
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (216, 200, 38, 84)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (217, 400, 38, 53)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (218, 100, 38, 25)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (219, 100, 38, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (220, 50, 38, 59)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (221, 50, 38, 62)")
    # Инсалата Каппоне
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (222, 200, 39, 44)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (223, 120, 39, 8)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (224, 100, 39, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (225, 200, 39, 53)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (226, 50, 39, 62)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (227, 30 , 39, 55)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (228, 30, 39, 20)")
    # Руккола с пармезаном
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (229, 200, 40, 64)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (230, 50, 40, 65)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (231, 30, 40, 20)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (232, 30, 40, 55)")
    # Оссобуко
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (233, 1600, 41, 89)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (234, 100, 41, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (235, 140, 41, 17)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (236, 80, 41, 80)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (237, 400, 41, 53)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (238, 250, 41, 2)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (239, 100, 41, 39)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (240, 30, 41, 55)")
    # Лазанья
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (241, 250, 42, 90)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (242, 400, 42, 91)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (243, 100, 42, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (244, 6, 42, 24)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (245, 800, 42, 53)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (246, 250, 42, 60)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (247, 100, 42, 65)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (248, 30, 42, 55)")
    # Полло алла Качаторра
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (249, 400, 43, 70)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (250, 100, 43, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (251, 12, 43, 24)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (252, 400, 43, 53)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (253, 100, 43, 92)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (254, 50, 43, 59)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (255, 30, 43, 55)")
    # Сальтимбокка
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (256, 600, 44, 35)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (257, 240, 44, 93)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (258, 400, 44, 41)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (259, 100, 44, 51)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (260, 50, 44, 49)")
    # Осьминог в собственном соку
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (261, 1000, 45, 94)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (262, 12, 45, 24)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (263, 30, 45, 55)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (264, 300, 45, 95)")
    # Фритто Мисто
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (265, 300, 46, 19)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (266, 100, 46, 39)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (267, 50, 46, 95)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (268, 120, 46, 8)")
    # Ризотто с морепродуктами
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (269, 200, 47, 19)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (270, 300, 47, 43)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (271, 100, 47, 34)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (272, 12, 47, 24)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (273, 100, 47, 51)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (274, 1000, 47, 2)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (275, 30, 47, 55)")
    # Фарфалле с лимонным крем-соусом и креветками
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (276, 300, 48, 96)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (277, 250, 48, 19)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (278, 150, 48, 95)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (279, 200, 48, 74)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (280, 12, 48, 24)")
    op.execute("INSERT INTO recipes_ingredients (id, weight, recipe_id, ingredients_id) VALUES (281, 30, 48, 55)")


def downgrade() -> None:
    op.execute("DELETE FROM countries WHERE name = 'Россия'")
    op.execute("DELETE FROM countries WHERE name = 'Япония'")
    op.execute("DELETE FROM countries WHERE name = 'Италия'")

    op.execute("DELETE FROM categories WHERE name = 'Супы'")
    op.execute("DELETE FROM categories WHERE name = 'Салаты'")
    op.execute("DELETE FROM categories WHERE name = 'Мясо")
    op.execute("DELETE FROM categories WHERE name = 'Рыба")

    op.execute("DELETE FROM ingredients WHERE name = 'Рамэн (лапша)'")
    op.execute("DELETE FROM ingredients WHERE name = 'Куриный бульон'")
    op.execute("DELETE FROM ingredients WHERE name = 'Соевый соус'")
    op.execute("DELETE FROM ingredients WHERE name = 'Мирин (рисовое вино)'")
    op.execute("DELETE FROM ingredients WHERE name = 'Имбирь'")
    op.execute("DELETE FROM ingredients WHERE name = 'Красный лук'")
    op.execute("DELETE FROM ingredients WHERE name = 'Шпинат'")
    op.execute("DELETE FROM ingredients WHERE name = 'Куриные яйца'")
    op.execute("DELETE FROM ingredients WHERE name = 'Куриное мясо'")
    op.execute("DELETE FROM ingredients WHERE name = 'Даш (водорослевый бульон)'")
    op.execute("DELETE FROM ingredients WHERE name = 'Паста мисо'")
    op.execute("DELETE FROM ingredients WHERE name = 'Тофу'")
    op.execute("DELETE FROM ingredients WHERE name = 'Зеленый лук'")
    op.execute("DELETE FROM ingredients WHERE name = 'Водоросли нори'")
    op.execute("DELETE FROM ingredients WHERE name = 'Удон (лапша)'")
    op.execute("DELETE FROM ingredients WHERE name = 'Грибы шитаке'")
    op.execute("DELETE FROM ingredients WHERE name = 'Морковь'")
    op.execute("DELETE FROM ingredients WHERE name = 'Лук-порей'")
    op.execute("DELETE FROM ingredients WHERE name = 'Креветки'")
    op.execute("DELETE FROM ingredients WHERE name = 'Лимонный сок'")
    op.execute("DELETE FROM ingredients WHERE name = 'Рыбный соус'")
    op.execute("DELETE FROM ingredients WHERE name = 'Том-ям паста'")
    op.execute("DELETE FROM ingredients WHERE name = 'Сахар'")
    op.execute("DELETE FROM ingredients WHERE name = 'Чеснок'")
    op.execute("DELETE FROM ingredients WHERE name = 'Огурец'")
    op.execute("DELETE FROM ingredients WHERE name = 'Японская майонезная заправка'")
    op.execute("DELETE FROM ingredients WHERE name = 'Кунжутная паста'")
    op.execute("DELETE FROM ingredients WHERE name = 'Кунжут'")
    op.execute("DELETE FROM ingredients WHERE name = 'Водоросли вакаме'")
    op.execute("DELETE FROM ingredients WHERE name = 'Рисовый уксус'")
    op.execute("DELETE FROM ingredients WHERE name = 'Кунжутное масло'")
    op.execute("DELETE FROM ingredients WHERE name = 'Тамари (подсоленный соевый соус)'")
    op.execute("DELETE FROM ingredients WHERE name = 'Растительное масло'")
    op.execute("DELETE FROM ingredients WHERE name = 'Луковица'")
    op.execute("DELETE FROM ingredients WHERE name = 'Говядина'")
    op.execute("DELETE FROM ingredients WHERE name = 'Шири-фундо (рисовая вермишель)'")
    op.execute("DELETE FROM ingredients WHERE name = 'Шинако (подсолнечные ростки)'")
    op.execute("DELETE FROM ingredients WHERE name = 'Свинные котлеты'")
    op.execute("DELETE FROM ingredients WHERE name = 'Мука'")
    op.execute("DELETE FROM ingredients WHERE name = 'Панировочные сухари'")
    op.execute("DELETE FROM ingredients WHERE name = 'Лосось'")
    op.execute("DELETE FROM ingredients WHERE name = 'Соль'")
    op.execute("DELETE FROM ingredients WHERE name = 'Рис'")
    op.execute("DELETE FROM ingredients WHERE name = 'Тунец'")
    op.execute("DELETE FROM ingredients WHERE name = 'Соус тереяки'")
    op.execute("DELETE FROM ingredients WHERE name = 'Филе семги'")
    op.execute("DELETE FROM ingredients WHERE name = 'Чёрная треска'")
    op.execute("DELETE FROM ingredients WHERE name = 'Саке'")
    op.execute("DELETE FROM ingredients WHERE name = 'Сливочное масло'")
    op.execute("DELETE FROM ingredients WHERE name = 'Говяжий бульон'")
    op.execute("DELETE FROM ingredients WHERE name = 'Белое вино'")
    op.execute("DELETE FROM ingredients WHERE name = 'Грюнгерский сыр'")
    op.execute("DELETE FROM ingredients WHERE name = 'Помидор'")
    op.execute("DELETE FROM ingredients WHERE name = 'Картофель'")
    op.execute("DELETE FROM ingredients WHERE name = 'Оливковое масло'")
    op.execute("DELETE FROM ingredients WHERE name = 'Красно винный уксус'")
    op.execute("DELETE FROM ingredients WHERE name = 'Устрицы'")
    op.execute("DELETE FROM ingredients WHERE name = 'Маслины'")
    op.execute("DELETE FROM ingredients WHERE name = 'Базилик'")
    op.execute("DELETE FROM ingredients WHERE name = 'Моцарелла'")
    op.execute("DELETE FROM ingredients WHERE name = 'Улитки'")
    op.execute("DELETE FROM ingredients WHERE name = 'Петрушка'")
    op.execute("DELETE FROM ingredients WHERE name = 'Ростбиф'")
    op.execute("DELETE FROM ingredients WHERE name = 'Руккола'")
    op.execute("DELETE FROM ingredients WHERE name = 'Пармезан'")
    op.execute("DELETE FROM ingredients WHERE name = 'Грецкие орехи'")
    op.execute("DELETE FROM ingredients WHERE name = 'Грибы'")
    op.execute("DELETE FROM ingredients WHERE name = 'Красное вино'")
    op.execute("DELETE FROM ingredients WHERE name = 'Бекон'")
    op.execute("DELETE FROM ingredients WHERE name = 'Куриная ножка'")
    op.execute("DELETE FROM ingredients WHERE name = 'Утиный жир'")
    op.execute("DELETE FROM ingredients WHERE name = 'Филе кролика'")
    op.execute("DELETE FROM ingredients WHERE name = 'Горчица'")
    op.execute("DELETE FROM ingredients WHERE name = 'Сливки'")
    op.execute("DELETE FROM ingredients WHERE name = 'Чёрный перец'")
    op.execute("DELETE FROM ingredients WHERE name = 'Рыба муллет'")
    op.execute("DELETE FROM ingredients WHERE name = 'Треска'")
    op.execute("DELETE FROM ingredients WHERE name = 'Капперсы'")
    op.execute("DELETE FROM ingredients WHERE name = 'Овощной бульон'")
    op.execute("DELETE FROM ingredients WHERE name = 'Стебель сельдерея'")
    op.execute("DELETE FROM ingredients WHERE name = 'Бобы'")
    op.execute("DELETE FROM ingredients WHERE name = 'Макаронные изделия'")
    op.execute("DELETE FROM ingredients WHERE name = 'Белая фасоль'")
    op.execute("DELETE FROM ingredients WHERE name = 'Хлеб'")
    op.execute("DELETE FROM ingredients WHERE name = 'Броколи'")
    op.execute("DELETE FROM ingredients WHERE name = 'Рыбный бульон'")
    op.execute("DELETE FROM ingredients WHERE name = 'Горох'")
    op.execute("DELETE FROM ingredients WHERE name = 'Майонез'")
    op.execute("DELETE FROM ingredients WHERE name = 'Телячья голень'")
    op.execute("DELETE FROM ingredients WHERE name = 'Лазанья'")
    op.execute("DELETE FROM ingredients WHERE name = 'Мясной фарш'")
    op.execute("DELETE FROM ingredients WHERE name = 'Оливки'")
    op.execute("DELETE FROM ingredients WHERE name = 'Ветчина'")
    op.execute("DELETE FROM ingredients WHERE name = 'Осьминог'")
    op.execute("DELETE FROM ingredients WHERE name = 'Лимон'")
    op.execute("DELETE FROM ingredients WHERE name = 'Фарфалле'")

    op.execute("DELETE FROM recipes WHERE title = 'Рамэн'")
    op.execute("DELETE FROM recipes WHERE title = 'Мисо суп'")
    op.execute("DELETE FROM recipes WHERE title = 'Удон суп'")
    op.execute("DELETE FROM recipes WHERE title = 'Том ям'")
    op.execute("DELETE FROM recipes WHERE title = 'Салат с японской майонезной заправкой'")
    op.execute("DELETE FROM recipes WHERE title = 'Гома-э дофу (салат с кунжутным соусом)'")
    op.execute("DELETE FROM recipes WHERE title = 'Салат с водорослями'")
    op.execute("DELETE FROM recipes WHERE title = 'Салат с огурцом и сезамом'")
    op.execute("DELETE FROM recipes WHERE title = 'Тереяки с курицей'")
    op.execute("DELETE FROM recipes WHERE title = 'Сукияки'")
    op.execute("DELETE FROM recipes WHERE title = 'Тонкацу (свиные отбивные)'")
    op.execute("DELETE FROM recipes WHERE title = 'Якитори (куриные шашлычки)'")
    op.execute("DELETE FROM recipes WHERE title = 'Суши с лососем'")
    op.execute("DELETE FROM recipes WHERE title = 'Терияки с тунцом'")
    op.execute("DELETE FROM recipes WHERE title = 'Яки-сакана (гриль семги)'")
    op.execute("DELETE FROM recipes WHERE title = 'Мисо-глазированный черный код'")
    op.execute("DELETE FROM recipes WHERE title = 'Луковый суп (Soupe à l'oignon)'")
    op.execute("DELETE FROM recipes WHERE title = 'Буйабес (Bouillabaisse)'")
    op.execute("DELETE FROM recipes WHERE title = 'Гаспачо (Gazpacho)'")
    op.execute("DELETE FROM recipes WHERE title = 'Устричный суп'")
    op.execute("DELETE FROM recipes WHERE title = 'Ницца (Salade Niçoise)'")
    op.execute("DELETE FROM recipes WHERE title = 'Капрезе (Salade Caprese)'")
    op.execute("DELETE FROM recipes WHERE title = 'Салат с улитками (Salade aux Escargots)'")
    op.execute("DELETE FROM recipes WHERE title = 'Салат с ростбифом (Salade de Roastbeef)'")
    op.execute("DELETE FROM recipes WHERE title = 'Беф Бургиньон (Boeuf Bourguignon)'")
    op.execute("DELETE FROM recipes WHERE title = 'Курица в вине (Coq au Vin)'")
    op.execute("DELETE FROM recipes WHERE title = 'Конфит утки (Canard Confît)'")
    op.execute("DELETE FROM recipes WHERE title = 'Филе молодого кролика с горчичным соусом'")
    op.execute("DELETE FROM recipes WHERE title = 'Лосось в соусе бурбланк (Saumon à la Bourguignonne)'")
    op.execute("DELETE FROM recipes WHERE title = 'Тунец в перцевой корке (Thon en Croûte de Poivre)'")
    op.execute("DELETE FROM recipes WHERE title = 'Муллет винный (Mulet au Vin Rouge)'")
    op.execute("DELETE FROM recipes WHERE title = 'Филе трески с пюре из картофеля и соусом из лимона и каперсов'")
    op.execute("DELETE FROM recipes WHERE title = 'Минестроне'")
    op.execute("DELETE FROM recipes WHERE title = 'Риболлита'")
    op.execute("DELETE FROM recipes WHERE title = 'Крем-суп с брокколи'")
    op.execute("DELETE FROM recipes WHERE title = 'Зуппа ди песче'")
    op.execute("DELETE FROM recipes WHERE title = 'Панзанелла'")
    op.execute("DELETE FROM recipes WHERE title = 'Инсалата Русса'")
    op.execute("DELETE FROM recipes WHERE title = 'Инсалата Каппоне'")
    op.execute("DELETE FROM recipes WHERE title = 'Руккола с пармезаном'")
    op.execute("DELETE FROM recipes WHERE title = 'Оссобуко'")
    op.execute("DELETE FROM recipes WHERE title = 'Лазанья'")
    op.execute("DELETE FROM recipes WHERE title = 'Полло алла Качаторра'")
    op.execute("DELETE FROM recipes WHERE title = 'Сальтимбокка'")
    op.execute("DELETE FROM recipes WHERE title = 'Осьминог в собственном соку'")
    op.execute("DELETE FROM recipes WHERE title = 'Фритто Мисто'")
    op.execute("DELETE FROM recipes WHERE title = 'Ризотто с морепродуктами'")
    op.execute("DELETE FROM recipes WHERE title = 'Фарфалле с лимонным крем-соусом и креветками'")

    op.execute("DELETE FROM recipes_ingredients WHERE id = 1")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 2")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 3")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 4")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 5")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 6")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 7")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 8")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 9")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 10")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 11")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 12")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 13")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 14")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 15")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 16")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 17")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 18")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 19")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 20")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 21")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 22")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 23")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 24")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 25")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 26")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 27")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 28")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 29")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 30")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 31")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 32")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 33")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 34")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 35")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 36")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 37")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 38")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 39")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 40")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 41")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 42")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 43")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 44")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 45")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 46")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 47")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 48")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 49")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 50")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 51")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 52")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 53")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 54")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 55")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 56")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 57")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 58")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 59")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 60")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 61")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 62")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 63")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 64")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 65")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 66")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 67")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 68")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 69")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 70")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 71")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 72")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 73")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 74")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 75")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 76")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 77")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 78")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 79")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 80")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 81")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 82")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 83")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 84")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 85")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 86")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 87")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 88")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 89")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 90")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 91")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 92")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 93")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 94")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 95")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 96")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 97")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 98")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 99")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 100")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 101")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 102")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 103")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 104")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 105")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 106")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 107")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 108")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 109")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 110")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 111")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 112")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 113")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 114")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 115")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 116")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 117")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 118")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 119")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 120")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 121")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 122")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 123")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 124")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 125")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 126")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 127")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 128")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 129")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 130")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 131")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 132")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 133")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 134")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 135")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 136")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 137")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 138")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 139")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 140")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 141")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 142")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 143")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 144")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 145")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 146")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 147")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 148")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 149")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 150")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 151")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 152")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 153")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 154")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 155")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 156")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 157")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 158")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 159")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 160")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 161")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 162")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 163")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 164")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 165")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 166")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 167")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 168")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 169")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 170")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 171")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 172")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 173")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 174")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 175")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 176")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 177")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 178")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 179")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 180")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 181")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 182")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 183")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 184")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 185")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 186")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 187")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 188")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 189")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 190")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 191")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 192")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 193")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 194")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 195")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 196")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 197")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 198")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 199")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 200")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 201")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 202")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 203")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 204")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 205")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 206")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 207")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 208")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 209")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 210")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 211")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 212")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 213")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 214")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 215")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 216")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 217")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 218")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 219")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 220")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 221")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 222")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 223")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 224")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 225")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 226")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 227")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 228")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 229")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 230")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 231")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 232")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 233")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 234")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 235")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 236")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 237")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 238")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 239")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 240")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 241")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 242")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 243")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 244")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 245")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 246")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 247")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 248")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 249")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 250")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 251")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 252")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 253")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 254")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 255")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 256")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 257")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 258")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 259")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 260")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 261")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 262")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 263")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 264")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 265")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 266")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 267")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 268")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 269")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 270")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 271")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 272")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 273")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 274")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 275")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 276")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 277")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 278")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 279")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 280")
    op.execute("DELETE FROM recipes_ingredients WHERE id = 281")
